//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelZaPse.Models.EFRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelZaPseDBEntities : DbContext
    {
        public HotelZaPseDBEntities()
            : base("name=HotelZaPseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminModel> AdminModels { get; set; }
        public virtual DbSet<PasModel> PasModels { get; set; }
        public virtual DbSet<RezervacijaModel> RezervacijaModels { get; set; }
        public virtual DbSet<UslugaModel> UslugaModels { get; set; }
        public virtual DbSet<VlasnikModel> VlasnikModels { get; set; }
    }
}
