//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelZaPse.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class RezervacijaModel
    {
        public int rezervacijaID { get; set; }
        public System.DateTime datumPrijavljivanja { get; set; }
        public System.DateTime datumOdjavljivanja { get; set; }
        public string napomena { get; set; }
        public double cena { get; set; }
        public int uslugaID { get; set; }
        public int vlasnikID { get; set; }
        public int pasID { get; set; }
    
        public virtual PasModel Pas { get; set; }
        public virtual UslugaModel Usluga { get; set; }
    }
}
