//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelZaPse.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UslugaModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UslugaModel()
        {
            this.Rezervacijas = new HashSet<RezervacijaModel>();
        }
    
        public int uslugaID { get; set; }
        public string naziv { get; set; }
        public double cena { get; set; }
        public string opis { get; set; }
        public int kapacitet { get; set; }
        public bool aktivna { get; set; }
        public int adminID { get; set; }
    
        public virtual AdminModel Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezervacijaModel> Rezervacijas { get; set; }
    }
}
